#
#  Author: Hari Sekhon
#  Date: 2020-02-24 16:19:35 +0000 (Mon, 24 Feb 2020)
#
#  vim:ts=4:sts=4:sw=4:et
#
#  https://github.com/harisekhon/bash-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

# https://www.appveyor.com/docs/appveyor-yml/

image: Ubuntu

install:
- sudo apt update
- sudo apt install -y git make
- make

test_script:
- make test

build: off
