#
#  Author: Hari Sekhon
#  Date: 2020-02-24 16:19:35 +0000 (Mon, 24 Feb 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/bash-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

# https://www.appveyor.com/docs/appveyor-yml/

image: Ubuntu

environment:
  APPVEYOR_SSH_KEY: AAAAB3NzaC1yc2EAAAABIwAAAQEAvihSRU+YjBKvKiacDfUoZ7ghoVMcwNh4cWIYUNFGZosXOzNtyOcBpIb71TCgLFhOd+aMWKXCEC67BpNSIjt+a/FLD27AwmgVHv6cPlE3G0JJ9zmIrNmx9511dshTsxUW2O0SbYG+3InuO7FUkSrld+kA1OucyjgmZU7/+Cs9shpAEOaIVYmGlpDGRucAHpwtckvdgRTtnA3WNZ/Qg1vU6Ik4Xm03vjrW6lSiuTffYO1kbdcMQ4IZBlzfmovOtXQ0PomvN5NMCpgOyQuoNlvyS11tOXoqNiWOkiLE15XEzAQth9hHbNiH8jHJbAtkHqWWh0KK4IUyNGvoL6QfNxsTlw==

# enable SSH session accessible via my public key
init:
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

install:
# workaround for:
# Some packages could not be installed. This may mean that you have
# requested an impossible situation or if you are using the unstable
# distribution that some required packages have not yet been created
# or been moved out of Incoming.
# The following information may help to resolve the situation:
#
# The following packages have unmet dependencies:
#  mssql-server : Depends: libsasl2-modules-gssapi-mit but it is not going to be installed
#  E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
#  bash-tools/Makefile.in:272: recipe for target 'apt-packages' failed
#  make[2]: *** [apt-packages] Error 123
#  make[2]: Leaving directory '/home/appveyor/projects/pylib'
#  bash-tools/Makefile.in:212: recipe for target 'system-packages' failed
#
#  adding "|| :" to the end of these commands causes them to be silently ignored!
- sudo sed -i '/https:\/\/packages.microsoft.com\/ubuntu\/.*\/mssql-server/d' /etc/apt/sources.list
- sudo apt purge -qy --allow-change-held-packages mssql-server
- sudo apt update -qq
- sudo apt install -qy git make
- make

test_script:
- make test

build: off
