#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: Sun Feb 23 19:02:10 2020 +0000
#
#  https://github.com/HariSekhon/DevOps-Bash-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#  to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                               G i t L a b   C I
# ============================================================================ #

# https://docs.gitlab.com/ee/ci/yaml/README.html

#include: '.gitlab/*.y*ml'

image: ubuntu:18.04

job:
  before_script:
    - setup/ci_bootstrap.sh
  script:
    - make init && make ci test
