#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: Sun Feb 23 19:02:10 2020 +0000
#
#  https://github.com/harisekhon/bash-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#  to help improve or steer this or other code I publish
#
#  http://www.linkedin.com/in/harisekhon
#

# https://aka.ms/yaml

trigger:
- master

pool:
  # there is no /dev/stderr on this azure build!
  #vmImage: 'ubuntu-latest'
  # Ubuntu 16.04 required for docker container support, looks like 18.04 works too
  vmImage: 'ubuntu-18.04'

# unprivileged container without sudo, cannot install dependencies
#container: ubuntu:18.04

steps:
# requires script as first key, otherwise parsing breaks with error message:  Unexpected value 'displayName'
- script: env | sort
  displayName: env

# doesn't work in container due to unprivileged execution and lack of sudo
#- script: sudo apt-get update && sudo apt-get install -y git make
#  displayName: install git & make

#- script: make
#  displayName: build

# doesn't work in vmImage build due to lack of access to normal /dev/stderr device
# tee: /dev/stderr: No such device or address
#- script: make test
#  displayName: test

# hacky workaround to Azure Pipelines ubuntu environment limitations of unprivileged container and no /dev/stderr in vmImage :-(
- script: sudo docker run -v "$PWD":/code ubuntu:18.04 /bin/bash -c 'set -ex && cd /code && setup/ci_bootstrap.sh && make init && make ci test'
  displayName: docker build
