#
#  Author: Hari Sekhon
#  Date: 2022-02-21 16:53:29 +0000 (Mon, 21 Feb 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/DevOps-Bash-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                          C h e c k o v   c o n f i g
# ============================================================================ #

# https://github.com/bridgecrewio/checkov#configuration-using-a-config-file
#
# This is not well documented but the fields seem to be the same as:
#
#   checkov --help
#
# See master template at:
#
#   https://github.com/HariSekhon/Templates/blob/master/.checkov.yaml

---
compact: true
directory:
  - .
skip-path:
  - sql
  - templates
  - vagrant/kubernetes/calico.yaml
  - vagrant/kubernetes/LFS258
docker-image: harisekhon/bash-tools
download-external-modules: true  # without this gets lots of annoying warning lines such as '2022-02-22 16:14:40,180 [MainThread  ] [WARNI]  Failed to download module x/y/z:n.n.n'
framework:
  - all
no-guide: true
output: cli
quiet: true
repo-id: HariSekhon/DevOps-Bash-tools  # what to report to Bridgecrew Cloud - without this gets annoying duplicate repos such as 'harisekhon_cli_repo/bash-tools'
skip-suppressions: true
soft-fail: true
