#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

name: CI CentOS

#env:
#  DEBUG: 1

on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 10 30 * *'

jobs:
  build:
    #name: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: centos
    env:
      repo: bash-tools
    steps:
    # untars repo in docker container so git submodule update fails
    #- uses: actions/checkout@v2
    - name: install git & make
      run: |
        ls -l /.dockerenv
        echo "pwd is $PWD"
        cat /etc/*release
        yum install -y git make
    - name: git clone
      run: |
        cd /tmp &&
        git clone "https://github.com/harisekhon/$repo"
    - name: build
      run: |
        cd "/tmp/$repo" &&
        ./retry.sh make
    - name: test
      run: |
        cd "/tmp/$repo" &&
        make test
