#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

name: CI Debian 6

#env:
#  DEBUG: 1

on: # [push]
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 10 30 * *'

jobs:
  build:
    #name: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: debian:6
    env:
      repo: bash-tools
    steps:
    # untars repo in docker container so git submodule update fails
    #- uses: actions/checkout@v2
    - name: switch apt sources to archive
      run: |
        sed -i 's/deb.debian.org/archive.debian.org/' /etc/apt/sources.list
    - name: install git & make
      run: |
        ls -l /.dockerenv
        echo "pwd is $PWD"
        echo VERSION: ; cat /etc/*release /etc/*version 2>/dev/null || :
        apt-get update || :  # will fail on security updates
        apt-get install -y git make
    - name: git clone
      run: |
        cd /tmp &&
        git clone "https://github.com/harisekhon/$repo"
    - name: build
      run: |
        cd "/tmp/$repo" &&
        make
    - name: test
      run: |
        cd "/tmp/$repo" &&
        make test
