#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Debian 8

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false  # build auto-cancellation - enabling this causes false-positive badge failure statuses

jobs:
  build:
    name: Debian 8
    uses: HariSekhon/GitHub-Actions/.github/workflows/debian.yaml@master
    with:
      version: 8
      #debug: 1
