#
#  Author: Hari Sekhon
#  Date: 2022-01-27 18:55:16 +0000 (Thu, 27 Jan 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/DevOps-Bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Docker Build (Ubuntu)

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**/*.md'
      - .github/
      - '**/Dockerfile'
      - '**/Jenkinsfile'
      - '**/.envrc*'
      - .checkov.yaml
      - .dockerignore
      - .gcloudignore
      - .editorconfig
      - '.gitconfig*'
      - .gitignore
      - .grype.yaml
      - .hound.yml
      - .terraformignore
      - Jenkinsfile
      - .appveyor.yml
      - .buildkite/pipeline.yml
      - .circleci/config.yml
      - .cirrus.yml
      - .concourse.yml
      - .drone.yml
      - .gitlab-ci.yml
      - .gocd.yml
      - .scrutinizer.yml
      - .semaphore/semaphore.yml
      - .travis.yml
      - .werckerignore
      - azure-pipelines.yml
      - bitbucket-pipelines.yml
      - buddy.yml
      - buildspec.yml
      - cloudbuild.yaml
      - codefresh.yml
      - codeship.yml
      - shippable.yml
      - wercker.yml
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - '**/*.md'
      - .github/
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docker_build:
    # github.event.repository context not available in scheduled workflows
    if: |
      github.repository_owner == 'HariSekhon' &&
      github.ref_type == 'branch' &&
      ( github.ref_name == github.event.repository.default_branch || github.ref_name == 'docker' )
    name: Docker Build
    uses: HariSekhon/GitHub-Actions/.github/workflows/docker_build.yaml@master
    with:
      # GitHub Actions doesn't yet support referencing env context in uses
      repo_tags: |
        harisekhon/bash-tools:latest
        harisekhon/bash-tools:ubuntu
        ghcr.io/harisekhon/bash-tools:latest
        ghcr.io/harisekhon/bash-tools:ubuntu
      dockerfile-repo: HariSekhon/Dockerfiles
      context: Dockerfiles/devops-bash-tools-ubuntu
      debug: ${{ github.event.inputs.debug }}
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
