#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/DevOps-Bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Fork Update

on:
  workflow_dispatch:
    inputs:
      debug:
        type: string
        required: false
  schedule:
    - cron: '0 10 * * 2'

jobs:
  fork_update:
    name: Fork Update
    uses: HariSekhon/GitHub-Actions/.github/workflows/fork-update.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
    permissions:
      contents: write
      pull-requests: write
