#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/DevOps-Bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                                    J S O N
# ============================================================================ #

# Validate any JSON files found in the repo

---
name: JSON

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.json'
      - .github/workflows/json.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.json'
      - .github/workflows/json.yaml
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  check_json:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Check JSON
    uses: HariSekhon/GitHub-Actions/.github/workflows/json.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
