#
#  Author: Hari Sekhon
#  Date: 2023-04-14 23:53:43 +0100 (Fri, 14 Apr 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/DevOps-Bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                                M a r k D o w n
# ============================================================================ #

---
name: Markdown

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.md'
      - .mdlrc
      - .mdl.rb
      - .markdownlint.rb
      - .github/workflows/markdown.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.md'
      - .mdlrc
      - .mdl.rb
      - .markdownlint.rb
      - .github/workflows/markdown.yaml
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  Markdown:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Markdown
    uses: HariSekhon/GitHub-Actions/.github/workflows/markdown.yaml@master
