#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: GitHub Actions Ubuntu

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository_owner == 'HariSekhon'
    name: GitHub Ubuntu
    uses: HariSekhon/GitHub-Actions/.github/workflows/ubuntu_github.yaml@master
    #with:
    #  debug: 1
